<div class="span-18 last newsListing">
<?php echo $this->listToolsForm;?>
<div class="span-18 last midAlign"><?php
echo $this->paginator;
?></div>
<table class='spreadsheet' cellspacing='0'>
	<tr>
		<th>&nbsp;</th>
		<th>Date</th>
		<th>Priority</th>
		<th>Status</th>
		<th>URL</th>
		<th>Submitter</th>
		<th>Description</th>
	</tr>
<?php
foreach ($this->bugs as $bugs) {
    ?>
	<tr>
		<td><a
			href='/admin/bugs/delete/id/<?php
    echo $bugs->id;
    ?>'>Delete</a></td>
		<td><?php
    echo date('m/d/y', $bugs->date);
    ?></td>
		<td><?php
    echo $bugs->priority;
    ?></td>
		<td><?php
    echo $bugs->status;
    ?></td>
		<td><?php
    echo $bugs->url;
    ?></td>
		<td><?php
    echo $bugs->author;
    ?></td>
		<td><?php
    echo $bugs->description;
    ?></td>
	</tr>
<?php } ?>

</table>
<div class="span-18 last midAlign"><?php
echo $this->paginator;
?></div>
</div>
