<div align="center"><span style="font-weight: bold; font-size: 18px;">Are
you sure you want to delete <span style="color: blue;"><i><?php echo $this->articleTitle; ?></i></span>?
This cannot be undone!!</span></div>
<br />
<br />
<div align="center"><a
	href="/members/submissions/delete/sid/<?php echo $this->sid; ?>/confirm/1">YES</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a
	href="/members/submissions/view">NO</a></div>
