<?php foreach($this->news as $story){ ?>
<div class="span-18 last newsListing">
	<div class="span-15 newsListTitle"> <a href="/view/article/sid/<?php echo $story['id']; ?>"><?php echo $story['title']; ?></a>
	</div>
	<div class="span-2 last newsListAction"><a href="/members/submissions/edit/sid/<?php echo $story['id']; ?>">Edit</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/members/submissions/delete/sid/<?php echo $story['id']; ?>">Delete</a>
	</div>
</div>
<?php } ?>
<div class="span-18 last midAlign">
<?php
echo $this->paginationControl($this->paginator, 'Elastic', 'pagination.phtml');
?>
</div>
