<?php
foreach ($this->news as $story) {
    ?>
<table style="border: solid 1px black" width="95%">
	<tr>
		<td colspan=3 style="border: solid 1px black" align="center"><a
			href="/view/article/sid/<?php
    echo $story->id;
    ?>"><?php
    echo $this->escape($story->title);
    ?></a></td>
	</tr>
	<tr>
		<td style="border: solid 1px black">Author: <?php
    echo $story->author;
    ?></td>
		<td style="border: solid 1px black">Created: <?php
    echo $story->created;
    ?></td>
		<td style="border: solid 1px black">Views: <?php
    echo $story->views;
    ?></td>
	</tr>
	<tr>
		<td style="border: solid 1px black" colspan="3"><?php
    echo $story->summary;
    ?><br>
		<br>
		&nbsp;&nbsp;&nbsp;<a
			href="/view/article/sid/<?php
    echo $story->id;
    ?>">Read More</a></td>
	</tr>
</table>
<br />
<?php } ?>
