<div class="span-18 last adminCat">
	Database Settings
</div>
<div class="span-16 push-1 last adminCont">
	<div class="span-16 last adminList">
		<div class="span-8 adminLeft">Database Host: </div>
		<div class="span-7 last adminRight"><?php echo $this->dbHost ?></div>
	</div>
	<div class="span-16 last adminList">
		<div class="span-8 adminLeft">Database User: </div>
		<div class="span-7 last adminRight"><?php echo $this->username ?></div>
	</div>
	<div class="span-16 last adminList">
		<div class="span-8 adminLeft">Database Password: </div>
		<div class="span-7 last adminRight"><?php echo $this->password ?></div>
	</div>
	<div class="span-16 last adminListBot">
		<div class="span-8">Database Name: </div>
		<div class="span-7 last adminRight"><?php echo $this->dbName ?></div>
	</div>
</div>

<div class="span-18 last adminCat">
	Header/Footer Settings
</div>
<div class="span-16 push-1 last adminCont">
	<div class="span-16 last adminList"><div class="span-8 adminLeft">Site Name: </div><div class="span-7 last adminRight"><?php echo $this->siteName ?></div></div>
	<div class="span-16 last adminList"><div class="span-8 adminLeft">Site Slogan: </div><div class="span-7 last adminRight"><?php echo $this->siteSlogan ?></div></div>
	<div class="span-16 last adminList"><div class="span-8 adminLeft">Comapny Name for footer: </div><div class="span-7 last adminRight"><?php echo $this->footerName ?></div></div>
	<div class="span-16 last adminListBot"><div class="span-8">Company URL for footer: </div><div class="span-7 last adminRight"><?php echo $this->footerLink ?></div></div>
</div>
<div class="span-18 last adminCat">
News Item Settings
</div>
	<div class="span-16 push-1 last adminCont">
	<div class="span-16 last adminList"><div class="span-8 adminLeft">Latest News story limit: </div><div class="span-7 last adminRight"><?php echo $this->dbHost ?></div></div>
	<div class="span-16 last adminList"><div class="span-8 adminLeft">Popular News story limit: </div><div class="span-7 last adminRight"><?php echo $this->username ?></div></div>
	<div class="span-16 last adminListBot"><div class="span-8">Story limit for Paginated pages: </div><div class="span-7 last adminRight"><?php echo $this->password ?></div></div>
</div>
<div class="span-18 last midAlign"><a href="/admin/settings/edit">Modify Settings</a></div>