<html><head><META content="text/html; charset=ISO-8859-1" http-equiv=Content-Type>


<!--meta_begin-->

<title></title>

<meta name="description" content="EternalCMS">

<meta name="keywords" content="EternalCMS">
        <style>
body{                                  
    background-color: #F5FFFA;
    color: black;
    margin: 0px;
}
.navig{
    height: 20px;
    background: url(/images/img/navig/ng25.gif) no-repeat; 
    text-align: left; 
    font-weight: bold; 
    color: black;
    font-size: 10px;
    vertical-align: middle;
    text-indent: 15px;
    font-family: sans-serif;
}
.navighead{
    height: 20px;
    background: url(/images/img/navig/ngr25.gif) no-repeat; 
    text-align: left; 
    font-weight: bold; 
    color: white;
    font-size: 12px;
    vertical-align: top;
    text-indent: 5px;
}
.errors{
color: red;
font-weight: bold;
list-style-type: none;
}

.required:after{content:' *'}

.navig A:link {text-decoration: none; color: black}
.navig A:visited {text-decoration: none; color: black} 
.navig A:active {text-decoration: none; color: black} 
.navig A:hover {text-decoration: none; color: black} 
.navighead A:link {text-decoration: none; color: white}
.navighead A:visited {text-decoration: none; color: white} 
.navighead A:active {text-decoration: none; color: white} 
.navighead A:hover {text-decoration: none; color: white} 
.tableheader1 {  font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: normal; font-weight: bold; color: #000000; text-decoration: none; background-color: #CCCCCC}
.pageheader {  font-family: Arial, Helvetica, sans-serif; font-size: 20px; font-weight: bold; color: #566F3A; text-decoration: none; text-align: center; height: 40px; vertical-align: top;}
</style>
<!--meta_end--></head>

<!--header_begin-->
<BODY bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">

<!--header_end-->

<!--mt_begin-->
<TR>
      <TD align="left" valign="top" width="95%" background="/images/img/base/ba51.gif"><span style="margin-left:10; color:white; font-weight:bolder; font-size:28px;"><?php echo $this->siteName; ?></span><BR>

       <span style="margin-left: 300px; font-weight:bold; font-size:20px;"><?php echo $this->slogan; ?></span></TD>



<!--st_end-->

<!--main_begin-->

   </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0" height="77%">
   <TR> 
      <TD align="left" valign="top" width="5%" background="/images/img/base/ba52.gif"> 
         <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">


<!--main_end-->

<!--home_begin-->
<TR>               <TD align="left" valign="top" height="30"><A><IMG src="/images/img/base/ba4.gif" width="134" height="22" name="home" border="0"></A></TD>          </TR>

<!--home_end-->

<!--navig_begin-->
<?php
$menu = $this->GenerateMenu($this->user);
foreach($menu as $item){ ?>
<TR> 
               <TD class="<?=$item['type']; ?>"><a href="<?=$item['uri']; ?>"><?=$item['label']; ?></a></TD>
            </TR>
            <?php } ?>
 

     </TABLE>      </TD>      <TD align="right" valign="top" width="95%">
         
         <table width="100%" border="1" cellspacing="0" cellpadding="0">
<tr><td align="center">Welcome, <?php if(isset($this->user)){ echo $this->user->uname; }else{ ?>Guest<?php } ?></td></tr></table>
<TABLE width="90%" border="0" cellspacing="0" cellpadding="0" align="center">
            <TR>
               <TD align="left" valign="top">



<div class="pageheader"><?php
    echo $this->title;
    ?>
                </div>
          <?php
        echo $this->layout()->content;
        ?>
<!--contentEnd-->

<!--banner_begin-->

</TD>
            </TR>
         </TABLE>
      </TD>
   </TR>
   <TR> 
      <TD align="left" valign="top" width="5%" background="/images/img/base/ba52.gif" height="20">&nbsp;</TD>
      <TD align="center" valign="top" width="95%" height="20">&nbsp;</TD>
   </TR>


<!--banner_end-->

<!--footer_begin-->
<TR> 
      <TD align="left" valign="top" width="5%" background="/images/img/base/ba52.gif">&nbsp;</TD>
      <TD align="center" valign="top" width="95%"><div style="text-align: center;"><font size="1">Copyright ©2009 - <a id="w1233730090088" href="http://www.jplwebsolutions.com">JPL Web Solutions</a>.&nbsp; All Rights Reserved</font></div>&#10;&#10;&#10;<link type="text/css" rel="stylesheet" href="css/default.css"></TD>
   </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
   <TR>
      <TD align="left" valign="top" width="5%" background="/images/img/base/ba53.gif"><IMG src="/images/img/base/ba52.gif" width="134" height="8"></TD>
      <TD align="right" valign="top" width="95%" background="/images/img/base/ba55.gif"><IMG src="/images/img/base/ba54.gif" width="366" height="65"></TD>
   </TR>
</TABLE>


<!--footer_end-->

<!--dfooter_begin-->
</BODY>
</HTML>


<!--dfooter_end-->
